name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!

  - type: dropdown
    id: type
    attributes:
      label: Request Type
      options:
        - New Component
        - New Feature for Existing Component
        - New Hook/Composable
        - Design Token
        - Other
    validations:
      required: true

  - type: dropdown
    id: framework
    attributes:
      label: Framework
      description: Which framework(s) should this feature support?
      multiple: true
      options:
        - React
        - Vue
        - All

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Describe the feature you'd like
      placeholder: What do you want to achieve?
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Why do you need this feature?
      placeholder: Describe the problem this would solve

  - type: textarea
    id: api
    attributes:
      label: Proposed API
      description: If you have ideas about the API, share them here
      render: tsx
